### ISSUE TITLE
AttributeError: 'MapsConfig' object has no attribute 'default_location'

### ISSUE THREAD

**Issue by zopyx** [collective/plone.formwidget.geolocation#1]
I am receiving this error with Plone 4.3.2, plone.app.contenttypes and Dexterity and collective.geolocationbehavior installed.

On fresh site I added the behaviour to the 'Page' type. This error occurs
directly choosing "Page" from the "Add" dropdown menu.

Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module plone.z3cform.layout, line 66, in __call__
Module plone.z3cform.layout, line 50, in update
Module plone.dexterity.browser.add, line 112, in update
Module plone.z3cform.fieldsets.extensible, line 59, in update
Module plone.z3cform.patch, line 30, in GroupForm_update
Module z3c.form.group, line 128, in update
Module z3c.form.form, line 134, in updateWidgets
Module z3c.form.field, line 277, in update
Module plone.formwidget.geolocation.widget, line 20, in update
Module plone.formwidget.geolocation.widget, line 25, in _default_loc
AttributeError: 'MapsConfig' object has no attribute 'default_location'

**Comment by davilima6** [comment]
Invalid after removing dependency on Products.Maps.
