### ISSUE TITLE
Map search widget is not usable at all

### ISSUE THREAD

**Issue by laulaz** [collective/plone.formwidget.geolocation#45]
The search widget allows you to zoom on an address (with marker on it).
But you can not move the marker, nor add a new one, nor does it change the selected latitude / longitude fields.
IOW : address search does not help for anything, you cannot set any location.

**See demo :**
![Jan-20-2023 11-33-38](https://user-images.githubusercontent.com/1101273/213674771-6eac03c7-865a-4376-afdd-25a2dfbd9762.gif)

Also, there is another bug (much less severe) : if you search for an address, then choose to remove the marker, then search for the same address, you see 2 markers instead of 1.

**See demo :**
![Jan-20-2023 11-32-55](https://user-images.githubusercontent.com/1101273/213674587-9db8715b-77e2-4820-8155-69368592ce1e.gif)

I checked all previous versions : it was working for versions prior to 3.0.
@petschki any idea why ?

**Comment by petschki** [comment]
While working on the default value fix #59 I tried to reproduce the first issue but could not...  maybe it was because of the map initialization problem. can you try this PR?
